// const store = require('../store');
const path           = require('path');
const fs             = require('fs');
const { v1: uuidv1 } = require('uuid');
const ioStream = require('socket.io-stream');

const assetsFolder = __dirname + '/../store/assets/';


function randomFileName(){
    return uuidv1() + '.png';
}

module.exports = function(io, socket, store){
    // content sharing
	socket.on('share-content', ({data, fileName, stream}) => {
		store.rooms.temp.socketId = socket.id;
		store.rooms.temp.requests = [];

		if (stream){
			const autogeneratedName = randomFileName();
			store.rooms.temp.stream = data;
			store.rooms.temp.fileName = fileName ? fileName : autogeneratedName;

			stream.pipe(fs.createWriteStream( assetsFolder + store.rooms.temp.fileName));
		} else {
			store.rooms.temp.data = data;
		}

		if (fileName){
			store.rooms.temp.fileName = fileName;
		}

        setTimeout( () => {
            store.archived.push(store.rooms.temp);
            store.rooms.temp = {};
		}, store.tempDelay)

		socket.in('dashboard').emit('share', {
			socket: socket.id,
			share: 'content',
			data
		})
	})
    
    socket.on('request-content', () => {

		socket.in('dashboard').emit('request', {
			socket: socket.id,
			request: 'content'
		})

		if (store.rooms.temp.data){
			store.rooms.temp.requests.push(socket.id);
		
			if (store.rooms.temp.stream){
				ioStream(socket).emit('get-stream', {
					stream : store.rooms.temp.stream,
					fileName: store.rooms.temp.fileName,
					socketId: store.rooms.temp.socketId
				}, stream, {name: store.rooms.temp.fileName})
				fs.createReadStream(assetsFolder + store.rooms.temp.fileName).pipe(stream);

			} else if (store.rooms.temp.fileName){
				socket.emit('get-content', {
					content : store.rooms.temp.data,
					fileName: store.rooms.temp.fileName,
					socketId: store.rooms.temp.socketId
				})

			} else {
				socket.emit('get-content', {
					content : store.rooms.temp.data,
					socketId: store.rooms.temp.socketId
				})
			}
		} else {
			socket.emit('send-message', {
				message: 'The cache is empty.' + store.rooms
			})
		}
    })
}