cache: npm

os:
  - osx
  - linux

osx_image:
  - xcode11

dist: bionic

language: node_js

node_js:
  - lts/dubnium
  - 11
  - lts/erbium
  - 13
  - 14

services:
  - docker
  - xvfb

install:
  - "bash ./.build/setup_${TRAVIS_OS_NAME}.sh"
script:
  - "bash ./.build/run_${TRAVIS_OS_NAME}.sh"
