platform:
  - x64

image:
  - Visual Studio 2017

init:
  - git config --global core.autocrlf true

environment:
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "11"
    - nodejs_version: "12"
    - nodejs_version: "13"
    - nodejs_version: "14"

clone_folder: c:\projects\trailmix

install:
  - ps: Install-Product node $env:nodejs_version x64
  - node --version
  - cd c:\projects\trailmix
  - npm ci

build: off

test_script:
  - npm test
